name: Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

env:
  VALE_VERSION: "3.6.0"

jobs:
  run-ci:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ !github.event.pull_request.draft && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    steps:
      # If the condition above is not met, aka, the PR is not in draft status, then this step is skipped.
      # Because this step is part of the critical path, omission of this step will result in remaining CI steps not gettinge executed.
      # As of 8/8/2022 there is now way to enforce this beahvior in GitHub Actions CI.
      - run: exit 0

  requirements:
    runs-on: ubuntu-latest
    needs: run-ci
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Vale
        run: |
          URL="https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz"
          wget --quiet $URL --output-document vale.tar.gz
          tar -xzf vale.tar.gz
          chmod +x vale
          sudo mv vale /usr/local/bin/

      - name: Vale Version
        run: vale --version

      - name: Test Files Present?
        run: make required_files

      - name: Tests
        run: make tests
