on:
  workflow_call:
    inputs:
      version:
        description: "The version of the Vale to use"
        default: "3.9.1"
        type: string
        required: false
      vale_flags:
        description: "Flags to pass to Vale"
        default: "--glob=*.{md} --minAlertLevel=error"
        type: string
        required: false

jobs:
  vale:
    name: Writing Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Vale Check
        uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: added
          reporter: github-pr-review
          vale_flags: ${{ inputs.vale_flags }}
          fail_on_error: false
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
