on:
  workflow_call:
    inputs:
      version:
        description: "The version of the Vale to use"
        default: "3.9.1"
        type: string
        required: false
      directory:
        description: "The directories to check. Seperate using a commad. For example: 'docs,src'"
        default: "."
        type: string
        required: false

jobs:
  vale:
    name: Writing Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Vale Check
        uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: added
          reporter: github-pr-review
          vale_flags: --minAlertLevel=error
          fail_on_error: false
          version: ${{ inputs.version }}
          files: ${{ inputs.directory }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
